#!/usr/bin/env tsx
/**
 * Generates OSINT provider seed JSON files from the adapter registry.
 * Run: npm run generate:osint-seeds
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { listAdapterMeta } from '../src/providers/adapters/registry.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'prisma/seeds/providers/osint');
mkdirSync(outDir, { recursive: true });

const BASE_URLS: Record<string, string> = {
  'osint-minha-receita': 'https://minhareceita.org',
  'osint-brasilapi-cnpj': 'https://brasilapi.com.br',
  'osint-receitaws': 'https://www.receitaws.com.br',
  'osint-opencnpj': 'https://api.opencnpj.org',
  'osint-datajud-cnj': 'https://api-publica.datajud.cnj.jus.br',
  'osint-portal-da-transparencia': 'https://api.portaldatransparencia.gov.br',
  'osint-viacep': 'https://viacep.com.br',
  'osint-ibge-localidades': 'https://servicodados.ibge.gov.br',
  'osint-nominatim': 'https://nominatim.openstreetmap.org',
  'osint-disify': 'https://www.disify.com',
  'osint-hunter-io': 'https://api.hunter.io',
  'osint-libphonenumber': 'https://local',
  'osint-veriphone': 'https://api.veriphone.io',
  'osint-ofac-sdn': 'https://sanctionslistservice.ofac.treas.gov',
  'osint-opensanctions': 'https://api.opensanctions.org',
  'osint-pncp': 'https://pncp.gov.br',
  'osint-tcu-sancoes': 'https://portal.tcu.gov.br',
};

const STUB_REFS = new Set([
  'osint-tse-candidaturas',
  'osint-bnmp-3-0',
  'osint-dou',
  'osint-bigdata-corp',
  'osint-jusbrasil',
]);

const files: string[] = [];

for (const meta of listAdapterMeta()) {
  if (STUB_REFS.has(meta.adapterRef)) continue;

  const seed = {
    slug: meta.adapterRef,
    name: meta.name,
    baseUrl: BASE_URLS[meta.adapterRef] ?? 'https://example.com',
    httpMethod: 'GET',
    requestTemplate: {
      _providerMeta: {
        adapterRef: meta.adapterRef,
        outputMode: 'findings',
        phase: meta.phase,
        reliability: meta.reliability,
        findingCategory: meta.category,
      },
    },
    authType: 'none',
    authConfigRef: null,
    fieldMappings: [],
    supportedTypes: meta.accepts,
    isActive: true,
    priority: meta.phase === 'sync' ? 50 : 150,
  };

  const filename = `${meta.adapterRef}.json`;
  writeFileSync(join(outDir, filename), `${JSON.stringify(seed, null, 2)}\n`);
  files.push(`providers/osint/${filename}`);
}

const manifestPath = join(root, 'prisma/osint-seeds.manifest.ts');
const manifest = `/** Auto-generated by scripts/generate-osint-seeds.ts — do not edit by hand */\nexport const OSINT_SEED_FILES = ${JSON.stringify(files, null, 2)} as const;\nexport type OsintSeedFile = (typeof OSINT_SEED_FILES)[number];\n`;
writeFileSync(manifestPath, manifest);
console.log(`Generated ${files.length} OSINT seeds in prisma/seeds/providers/osint/`);
