export const RISK_FACTOR_DESCRIPTIONS: Record<string, string> = {
  RESTRICTIVE_LIST_HIT: 'Hit em lista restritiva ou CEIS',
  SANCTIONS_HIT: 'Hit em lista de sanções internacional',
  PEP_FLAG: 'PEP identificado',
  PJ_PEP_ENTITY: 'PEP identificado na entidade PJ',
  PJ_SANCTIONED: 'Empresa atualmente sancionada',
  CNPJ_IRREGULAR: 'CNPJ com situação cadastral irregular',
  CRIMINAL_RECORD: 'Antecedente criminal confirmado',
  BANKRUPTCY: 'Empresa em falência ou recuperação judicial',
  PROTEST_THRESHOLD: 'Protestos acima do limite',
  COLLECTIONS_PRESENCE: 'Presença em bases de cobrança',
  CERTIFICATE_NEGATIVE: 'Certidão negativa identificada',
  ESG_SLAVE_LABOR: 'Trabalho análogo à escravidão (MTE)',
  ENVIRONMENTAL_EMBARGO: 'Embargo ambiental ativo',
  UBO_HIGH_RISK: 'UBO com risco elevado',
  DATA_INCOMPLETE: 'Dados insuficientes para análise',
};
